POST http://localhost:4000/refresh_token
Content-Type: application/json
Cookie: jid3=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU4NzkwMDc0NywiZXhwIjoxNTg3OTAxNjQ3fQ.u-j0pv7cAMsVf4LFlXkG98BmBRLYCgRshBpQsTHK0z4

###  
POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query hello {
  hi
}
###

POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Bearer xxx

mutation ($email: String! $password: String!) {
  login(email: $email, password: $password) {
    ok
    error
    token
  }
}

{
  "email": "kkh@nate.com",
  "password": "qwe123123"
}